entryPoints:
  web:
    address: ":80"

api:
  dashboard: true
  insecure: true



metrics:
  prometheus:
    entryPoint: metrics
    addEntryPointsLabels: true
    addServicesLabels: true

providers:
  file:
    directory: "/etc/traefik"
    watch: true
